#!/usr/bin/env python3
"""
render.py — com-artefact-viz CLI.

Render a canonical kit artefact (capability map, FBS, delivery roadmap, BMC) to
a single self-contained interactive HTML file.

    python render.py SOURCE.md [options]

Options:
    --out PATH              Output HTML path. Default:
                            docs/communication/visualisations/<kind>.html
    --kind KIND             Force the artefact kind
                            (capability-map | fbs | delivery-roadmap | bmc).
                            Auto-detected from path/content when omitted.
    --design-system PATH    Project design-system CSS to inline AFTER the
                            defaults (its :root tokens win — this is how a
                            project re-themes every view). Reuse the same
                            design/styles.css your com-slide-deck project uses.
    --left-axis-label TEXT  Override the capability-map / FBS left-axis label
                            (the directional "arrow" band). Defaults to the
                            artefact's declared L0 axis.
    --left-axis-arrow CHAR  Arrow glyph for that band (default "▼").
    --title TEXT            Override the page title.
    --detect                Print the detected kind and exit (no render).

Standard library only. Run from the repo root or anywhere — paths are resolved
relative to the current directory.
"""

import argparse
import datetime
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import parsers  # noqa: E402
import renderers  # noqa: E402

SKILL_DIR = os.path.dirname(HERE)
TEMPLATE_DIR = os.path.join(SKILL_DIR, "templates")


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def fill_template(slots):
    tmpl = _read(os.path.join(TEMPLATE_DIR, "base.html.tmpl"))
    for key, value in slots.items():
        tmpl = tmpl.replace("{{" + key + "}}", value)
    return tmpl


def build(source_path, args):
    text = _read(source_path)
    kind = args.kind or parsers.detect_kind(source_path, text)
    if not kind:
        sys.exit(
            f"error: could not detect artefact kind for {source_path!r}. "
            f"Pass --kind capability-map|fbs|delivery-roadmap|bmc."
        )
    if kind not in parsers.PARSERS:
        sys.exit(f"error: unknown kind {kind!r}.")

    if args.detect:
        print(kind)
        return None

    model = parsers.PARSERS[kind](text)
    options = {
        "left_axis_label": args.left_axis_label,
        "left_axis_arrow": args.left_axis_arrow,
    }
    rendered = renderers.RENDERERS[kind](model, options)

    # Design system: defaults first, then the project sheet (project tokens win).
    ds = _read(os.path.join(TEMPLATE_DIR, "design-system.css"))
    if args.design_system:
        ds += "\n\n/* ---- project design system (overrides) ---- */\n" + _read(args.design_system)

    runtime = _read(os.path.join(TEMPLATE_DIR, "runtime.js"))
    title = args.title or model["title"]
    today = datetime.date.today().isoformat()
    footer = (
        f'Generated by com-artefact-viz from '
        f'<code>{parsers_relpath(source_path)}</code> on {today}. '
        f'Source artefact is the single source of truth — re-render after edits.'
    )

    html = fill_template({
        "TITLE": _esc(title),
        "KIND": _esc(rendered["kind_label"]),
        "META": rendered["meta"],
        "TOOLBAR": rendered["toolbar"],
        "CONTENT": rendered["content"],
        "DESIGN_SYSTEM_CSS": ds,
        "VIEW_CSS": rendered["view_css"],
        "RUNTIME_JS": runtime,
        "FOOTER": footer,
    })

    out = args.out or default_out(kind)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(html)
    return out


def parsers_relpath(path):
    try:
        return os.path.relpath(path)
    except ValueError:
        return path


def _esc(s):
    import html
    return html.escape(s or "", quote=True)


def default_out(kind):
    return os.path.join("docs", "communication", "visualisations", f"{kind}.html")


def main(argv=None):
    ap = argparse.ArgumentParser(description="Render a kit artefact to interactive HTML.")
    ap.add_argument("source", help="Path to the source Markdown artefact.")
    ap.add_argument("--out")
    ap.add_argument("--kind", choices=sorted(parsers.PARSERS))
    ap.add_argument("--design-system", dest="design_system")
    ap.add_argument("--left-axis-label", dest="left_axis_label")
    ap.add_argument("--left-axis-arrow", dest="left_axis_arrow", default="▼")
    ap.add_argument("--title")
    ap.add_argument("--detect", action="store_true")
    args = ap.parse_args(argv)

    if not os.path.isfile(args.source):
        sys.exit(f"error: source not found: {args.source}")

    out = build(args.source, args)
    if out:
        print(f"wrote {out}")


if __name__ == "__main__":
    main()
